[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "*"
spin_sleep = "1.1.1"
rand = "0.8"

[profile.dev]
opt-level = 3
